CREATE TABLE IF NOT EXISTS `AUTHORITY`
(
    `ID`          TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `NAME`        VARCHAR(30) NOT NULL UNIQUE COMMENT '권한명',
    `DESCRIPTION` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '설명'
);
CREATE TABLE IF NOT EXISTS `DEPARTMENT`
(
    `ID`            TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `NAME`          VARCHAR(100)     NOT NULL UNIQUE COMMENT '부서명',
    `DESCRIPTION`   VARCHAR(255)     NOT NULL DEFAULT '' COMMENT '설명',
    `DEPARTMENT_ID` TINYINT UNSIGNED NULL     DEFAULT NULL COMMENT '상위부서 고유키',
    CONSTRAINT FK_DEPARTMENT_DEPARTMENT FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES DEPARTMENT (`ID`) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS `USER`
(
    `ID`                  INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `USERNAME`            VARCHAR(20)      NOT NULL UNIQUE COMMENT '유저 ID',
    `PASSWORD`            VARCHAR(255)     NOT NULL COMMENT '비밀번호(Bcrypt)',
    `NAME`                VARCHAR(50)      NOT NULL COMMENT '이름',
    `NICKNAME`            VARCHAR(50)      NOT NULL UNIQUE COMMENT '닉네임',
    `EMAIL`               VARCHAR(255)     NULL UNIQUE DEFAULT NULL COMMENT '이메일',
    `PHONE`               VARCHAR(13)      NULL UNIQUE DEFAULT NULL COMMENT '휴대폰',
    `ACCESS_IP`           VARCHAR(15)      NOT NULL    DEFAULT '*.*.*.*' COMMENT '로그인 가능 IP',
    `LOGIN_FAIL_IP`       VARCHAR(15)      NOT NULL    DEFAULT '' COMMENT '로그인 실패한 IP',
    `LOGIN_FAIL_COUNT`    TINYINT UNSIGNED NOT NULL    DEFAULT 0 COMMENT '로그인 실패 횟수',
    `STATUS_MESSAGE`      VARCHAR(255)     NOT NULL    DEFAULT '' COMMENT '상태 메시지',
    `BACKGROUND_IMAGE`    VARCHAR(255)     NOT NULL    DEFAULT '' COMMENT '배경 이미지',
    `PROFILE_IMAGE`       VARCHAR(255)     NOT NULL    DEFAULT '' COMMENT '프로필 이미지',
    `LOGIN_AT`            DATETIME         NOT NULL    DEFAULT NOW() COMMENT '로그인 시각',
    `LOGIN_FAILED_AT`     DATETIME         NOT NULL    DEFAULT '1970-01-01 09:00:00' COMMENT '로그인 실패 시각',
    `PASSWORD_CHANGED_AT` DATETIME         NULL        DEFAULT NOW() COMMENT '비밀번호 변경 시각',
    `CREATED_AT`          DATETIME         NOT NULL    DEFAULT NOW() COMMENT '생성 시각',
    `UPDATED_AT`          DATETIME         NOT NULL    DEFAULT '1970-01-01 09:00:00' COMMENT '수정 시각'
);

/* 1:1 Relation */
CREATE TABLE IF NOT EXISTS `USER_TOKEN`
(
    `ID`            INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `USER_ID`       INT UNSIGNED NOT NULL UNIQUE COMMENT '유저 고유키',
    `REFRESH_TOKEN` VARCHAR(200) NOT NULL UNIQUE COMMENT '리프레시 토큰',
    CONSTRAINT FK_USER_USER_TOKEN FOREIGN KEY (`USER_ID`) REFERENCES USER (`ID`) ON DELETE CASCADE
);

/* M:N Relation tables */
CREATE TABLE IF NOT EXISTS `USER_DEPARTMENT`
(
    `ID`            INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `USER_ID`       INT UNSIGNED     NOT NULL COMMENT '유저 고유키',
    `DEPARTMENT_ID` TINYINT UNSIGNED NOT NULL COMMENT '부서 고유키',
    CONSTRAINT FK_USER_DEPARTMENT_USER FOREIGN KEY (`USER_ID`) REFERENCES USER (`ID`) ON DELETE CASCADE,
    CONSTRAINT FK_USER_DEPARTMENT_DEPARTMENT FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES DEPARTMENT (`ID`) ON DELETE CASCADE,
    UNIQUE UK_USER_ID_DEPARTMENT_ID (`USER_ID`, `DEPARTMENT_ID`)
);
CREATE TABLE IF NOT EXISTS `USER_AUTHORITY`
(
    `ID`           INT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '고유키',
    `USER_ID`      INT UNSIGNED     NOT NULL COMMENT '유저 고유키',
    `AUTHORITY_ID` TINYINT UNSIGNED NOT NULL COMMENT '권한 고유키',
    CONSTRAINT FK_USER_AUTHORITY_USER FOREIGN KEY (`USER_ID`) REFERENCES USER (`ID`) ON DELETE CASCADE,
    CONSTRAINT FK_USER_AUTHORITY_AUTHORITY FOREIGN KEY (`AUTHORITY_ID`) REFERENCES DEPARTMENT (`ID`) ON DELETE CASCADE,
    UNIQUE UK_USER_ID_AUTHORITY_ID (`USER_ID`, `AUTHORITY_ID`)
);